# Site settings
title: Austin McGee
description: "Musings on life by Austin McGee!"
baseurl: ""
url: "http://austinmcgee.net"
linkedin_username: amcgee
github_username:  amcgee
instagram_username: awesleym

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
paginate_path: musings/page:num/
exclude: ["node_modules"]

# Plugins
plugins:
  - jekyll-redirect-from