# Site settings
title: Molto Vivo
email: me@austinmcgee.net
description: "Musings on life by Austin McGee!"
baseurl: ""
url: "http://austinmcgee.net"
twitter_username: awmcgee
github_username:  amcgee

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
