# Site settings
title: Austin McGee
description: "Musings on life by Austin McGee!"
baseurl: ""
url: "http://austinmcgee.net"
twitter_username: awmcgee
linkedin_username: amcgee
github_username:  amcgee
instagram_username: awesleym

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]

# Gems
gems:
  - jekyll-redirect-from